# Site settings
title: Point of Sale System
email: botha.daniel1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here you will find all the project notes for the Point Of Sale System
  I have developed for my Matric IT PAT for Paul Roos Gymnasium.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  iggnoreza

# Build settings
markdown: kramdown
